# Generated by Django 5.2.6 on 2025-11-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transactions",
            "0002_alter_transaction_description_alter_transaction_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
    ]
